### ISSUE TITLE
adjust ScrollView content size - swipable area

### ISSUE THREAD

**Issue by ghost** [jonathanxie/JXSwipeBetweenViews#1]
hi Jonathan, 

how would I edit JXSwipeBetweenViewControllers.swift  so that I can customize the swipable area - meaning the "content size" of the scroll view.  

i'd like to disable swiping and just use the buttons instead.

**Comment by jonathanxie** [comment]
Hi Jeff,

Working at the moment, but off the top of my head, try resizing the pageController:UIPageViewController to customize the swipe area.

For disabling swiping, you could look into using the "touchesShouldCancelInContentView" from: 

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIScrollView_Class/#//apple_ref/occ/instm/UIScrollView/touchesShouldCancelInContentView:


Hope this helps. I'll try and look into it later when I'm free

**Comment by jonathanxie** [comment]
@jeffvett 

So to disable swiping and just use the buttons instead just disable the enabled scrolling for the scrollview in the setUpPageViewController method. Look at the last line I added. I tested it on my iPhone 6 and it works. 

``` swift
    func setUpPageViewController() {
        pageController = self.topViewController as! UIPageViewController;
        pageController.delegate = self;
        pageController.dataSource = self;


        // Set the initial swipable view controller to the first one to match the currentPageIndex instance variable
        pageController.setViewControllers(
            [viewControllerArray[STARTING_INDEX]], // Set the initial swipable view ot the first one
            direction: UIPageViewControllerNavigationDirection.Forward, animated: true, completion: nil)

        syncScrollView();

        self.pageScrollView.scrollEnabled = false;
    }
```

**Comment by ghost** [comment]
Thanks Jonathan. Thanks for responding and great work on the navigation tool.  I also found that property in the documentation and implemented it successfully :)

I'm using button images instead of your font kit.  I want to add more button images to indicate which page is open.  For example, when current page = middle, then the buttons are white.  When the current page is the right or left, then button is colored.   Would I implement this in the scrollViewDidScroll function?

**Comment by jonathanxie** [comment]
yes, that would be the place to do so. Good luck on that =)

**Comment by ghost** [comment]
Hi Jonathan,

I've implemented this in a storyboard and it works great.  I'm just struggling to figure out how I can get back to the navigation after I go to a modal view.  I've tried an exit segue but it crashes on me.  Off the top of your head, do you know how I would re-enter the navigation controller where I left off?  For example if the left button was selected, can I return to the leftViewController?

thanks for sharing the great project!

-----Original Message-----

**Comment by jonathanxie** [comment]
I would probably have to see the code to see what your issue is exactly...

you're welcome =)

**Comment by ghost** [comment]
thanks for the reply.

My problem, put more simply is this:  If I click on the left button and go to the left viewController, then I go to a modal ViewController.  When I use dismissViewControllerAnimated from the modal screen, it goes back to the middle ViewController and adds the buttons again in the wrong location.  

Is this because you set the STARTING_INDEX variable to 1 every time the view loads?   

thanks

-----Original Message-----

**Comment by jonathanxie** [comment]
Yes, if you look at viewDidLoad you'll see me set the currentPageIndex to the STARTING_INDEX

``` swift

   override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.

        self.navigationBar.translucent = false;

        viewControllerArray = [UIViewController]()
        currentPageIndex = STARTING_INDEX; // Set it to the middle index of 1 since we're starting off there
        isPageScrollingFlag = false;
        hasAppearedFlag = false;

```

**Comment by ghost** [comment]
fyi, i solved the issue by moving some stuff between viewDidLoad and viewDidAppear.  simple fix.  

thanks again!

-----Original Message-----

**Comment by jonathanxie** [comment]
Great. Glad you figured it out =)
